name: 'Download latest NuGet (cross-platform)'
description: 'Cross-platform action that downloads the latest NuGet.exe and adds it to PATH.'
author: 'Oleg Tarasov'
inputs:
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'package'
  color: 'orange'